#!/bin/sh


uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system


uci set network.lan=interface
uci set network.lan.ifname='eth0'
uci set network.lan.proto='static'
#uci set network.lan.ipaddr='192.168.0.4'
uci set network.lan.ipaddr='192.168.50.3'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.gateway='192.168.50.1'
uci set network.lan.dns='202.102.224.68'
#uci set network.lan.type='bridge'

uci set network.wan = interface
uci set network.wan.ifname = 'eth0'
uci set network.wan.proto='none'

uci commit network

uci set dhcp.@dnsmasq[0].rebind_domain='plex.direct'


uci set dhcp.lan.ignore="1"

uci add dhcp domain
uci set dhcp.@domain[-1].name='xwhomeesxi.lan'
uci set dhcp.@domain[-1].ip='192.168.50.2'

uci commit dhcp



sed -i 's#root::0:0:99999:7:::#root:$1$9mi80fAa$o.d2j7HkjDBmhTp/..Oqq0:18271:0:99999:7:::#g' /etc/shadow

#uci set dhcp.lan.dhcpv6='server'
#uci set dhcp.lan.ra_management='1'
#uci set dhcp.lan.ra_default='1'
#uci commit dhcp

#sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
#echo "iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
#echo "iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user


#sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
#echo "DISTRIB_REVISION='R9.12.03'" >> /etc/openwrt_release
#sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
#echo "DISTRIB_DESCRIPTION='OpenWrt '" >> /etc/openwrt_release


rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0



