log:
  level: error
  file: '/var/log/mosdns.log'

plugin:

  ################# 服务插件 ################

  - tag: main_server      # 启动服务器
    type: server
    args:
      entry:
        - super_cache   # 缓存
        - add_ecs
        - main_sequence
        - ttl_set
      server:
        - protocol: udp
          addr: "[::]:53"
        - protocol: tcp
          addr: "[::]:53"
        - protocol: udp
          addr: '[::]:5335'
        - protocol: tcp
          addr: '[::]:5335'

  ################# 可执行插件 ################

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_ad_domain    # 已知的广告域名
          exec:
            - _block_with_nxdomain  # 用 NXDOMAIN 屏蔽
            - _end
            
        - if:
            - query_is_local_domain   # 已知的本地域名
            - '!_query_is_common'     # 和不常见的请求类型
          exec:
            - forward_local           # 用本地服务器
            - _end

        - if:
            - query_is_non_local_domain  # 已知的非本地域名
          exec:
            - forward_remote             # 用远程服务器
            - _end

        # 剩下的未知域名用 IP 分流。以下是"顺序 IP 分流"的逻辑。很稳定，不易出错。
        # <高级> 如果想用"并发 IP 分流"逻辑，从下文的 <并发 IP 分流示例> 里选择一个方案，
        # 然后将下面几行替换掉。
        - forward_local               # 先请求转发至本地服务器
        - if:
            - response_has_local_ip   # 如果(本地)应答包含本地 IP
          exec:
            - _end                    # 就直接采用结果
        - forward_remote              # 否则去请求远程服务器的结果

  - tag: forward_local                # 转发至本地服务器的插件
    type: fast_forward
    args:
      upstream:
        - addr: 202.102.224.68
        - addr: https://223.5.5.5/dns-query
        

  - tag: forward_remote               # 转发至远程服务器的插件
    type: fast_forward
    args:
      upstream:
        - addr: https://hkb.xwcoco.club/dns
          trusted: true
          dial_addr: '154.198.214.104:443'
        - addr: https://jp.xwcoco.club/dns
          dial_addr: '45.159.48.202:443'
          trusted: true            
        - addr: https://xwcoco.club/dns
          trusted: true
          dial_addr: '35.185.165.226:443'
        - addr: https://dev.xwcoco.club/dns
          trusted: true
          dial_addr: '34.92.144.66:443'
        - addr: https://1.0.0.1/dns-query
          dial_addr: '1.0.0.1:443'
          trusted: true    
        

  - tag: 'add_ecs'
    type: 'ecs'
    args:
      auto : false
      ipv4: '123.15.36.83'
      force_overwrite: true
      mask4: 24



  - tag: super_cache               # 超级缓存
    type: cache
    args:
      size: 102400
      cleaner_interval: 3600
      
  - tag: ttl_set
    type: ttl
    args:
      minimal_ttl: 3600  # 最小TTL。如果非零，小于这个数的应答的TTL会被修改成这个值。
      maximum_ttl: 7200 # 最大TTL。如果非零，大于这个数的应答的TTL会被修改成这个值。

  ################ 匹配器插件 #################

  - tag: query_is_local_domain         # 匹配本地域名的插件
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  - tag: query_is_non_local_domain    # 匹配非本地域名的插件
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  - tag: query_is_ad_domain           # 匹配广告域名的插件
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:category-ads-all'

  - tag: response_has_local_ip        # 匹配本地 IP的插件
    type: response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'
