#!/bin/sh
uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system



uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set network.lan=interface
uci set network.lan.ifname='eth0'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.0.68'
#uci set network.lan.ipaddr='192.168.50.6'
uci set network.lan.netmask='255.255.255.0'
#uci set network.lan.gateway='192.168.50.1'
uci set network.lan.gateway='192.168.0.1'
uci set network.lan.dns='202.102.224.68'
#uci set network.lan.type='bridge'
uci set network.lan.ipv6='off'

uci set network.wan = interface
uci set network.wan.ifname = 'eth0'
uci set network.wan.proto='none'

uci commit network

#uci set 'network.lan.ipv6=off'
#uci set 'network.wan.ipv6=off'
#uci set 'dhcp.lan.dhcpv6=disabled'

/etc/init.d/odhcpd disable

uci del dhcp.lan.start
uci del dhcp.lan.limit
uci del dhcp.lan.leasetime
uci del dhcp.lan.ra
uci del dhcp.lan.dhcpv6

uci set dhcp.lan=dhcp
uci set dhcp.lan.interface='lan'
uci set dhcp.lan.ignore="1"

uci set dhcp.wan=dhcp
uci set dhcp.wan.interface='wan'
uci set dhcp.wan.ignore='1'

uci commit dhcp

#sed -i 's/downloads.openwrt.org/openwrt.proxy.ustclug.org/g' /etc/opkg/distfeeds.conf
#sed -i 's/http/https/g' /etc/opkg/distfeeds.conf
sed -i 's#root::0:0:99999:7:::#root:$1$9mi80fAa$o.d2j7HkjDBmhTp/..Oqq0:18271:0:99999:7:::#g' /etc/shadow

#uci set dhcp.lan.dhcpv6='server'
#uci set dhcp.lan.ra_management='1'
#uci set dhcp.lan.ra_default='1'
#uci commit dhcp

#sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
#echo "iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
#echo "iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user

#sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
#echo "DISTRIB_REVISION='19.07'" >> /etc/openwrt_release
#sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
#echo "DISTRIB_DESCRIPTION='OpenWrt '" >> /etc/openwrt_release

#sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
#echo "DISTRIB_REVISION='R9.12.03'" >> /etc/openwrt_release
#sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
#echo "DISTRIB_DESCRIPTION='OpenWrt '" >> /etc/openwrt_release


exit 0



